### ISSUE TITLE
Product scraping

### ISSUE THREAD

**Issue by mpekris666** [LaskasP/E-food-Python-Scraper-2023#1]
Hey there,
Interesting work you've been up to!

May I ask, do you have any plans on adding product scraping as well?
Maybe even categorise products by menu categories, and even parse each products selections and options.

For example have `Freddo Espresso` product in `Coffees` category or even
`Freddo Espresso` product with `Sugar` selection and options `Sweet`, `Medium` and `No sugar`

**Comment by LaskasP** [comment]
Hey mpekri, 
Now there is no plan for further expansion due to limited time.
Your idea has a lot of potential and can be implemented in the future.
Do you need it for a specific reason?

**Comment by mpekris666** [comment]
Im sure lots would find this interesting in general. I for one would like to play around with a side project : )
Personally Im not really fluent in python, but if I find any free time, I might give it a try

**Comment by LaskasP** [comment]
Feel free to do it :)

Best
Petros
